// routes/courseRoutes.js
import express from "express";
import Course from "../models/Course.js";
const router = express.Router();

// Get all courses
router.get("/", async (req, res) => {
  const courses = await Course.find();
  res.json(courses);
});

// Create course (manual)
router.post("/", async (req, res) => {
  const { title, description, lessons, userId } = req.body;
  const course = new Course({ title, description, lessons, createdBy: userId });
  await course.save();
  res.json(course);
});

// AI-generated course (dummy example, integrate OpenAI API here)
router.post("/ai", async (req, res) => {
  const { subject } = req.body;
  // call AI API -> get course outline
  const course = new Course({
    title: `AI Course on ${subject}`,
    description: `This course covers basics of ${subject}.`,
    lessons: [{ title: "Introduction", content: "Generated by AI" }],
    aiGenerated: true
  });
  await course.save();
  res.json(course);
});

export default router;
